#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 24 21:14:00 2022

@author: edwardlu
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 22 09:48:32 2022

@author: edwardlu
"""

class cat():
    def __init__(self,name,weight,height,old):
        self.name = name
        self.weight = weight
        self.height = height
        self.old = old
        
    def bmi(self):
        b = self.weight/self.height/self.height
        return b
              
    cat = cat1('King.Glod.Lu',30,60,10)

print(cat.name)
print(cat.weight)
print(cat.height)
print(cat.old)

print("bmi:")

print(cat.bmi())
